{
 "title": "User Token Usage Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "MyScale Cluster", "query": "grafana-clickhouse-datasource" },
   { "name": "database", "label": "Database", "query": "SHOW DATABASES" },
   { "name": "table", "label": "Table", "query": "SHOW TABLES FROM $database" },
   {
    "name": "user_id",
    "label": "User ID",
    "query": "select distinct ResourceAttributes['user_id'] AS user_id from $database.$table where ResourceAttributes['user_id'] != ''"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Users by Total Prompt Token Usage",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    ResourceAttributes['user_id'] AS user_id,\n    sum(toUInt32(SpanAttributes['prompt_tokens'])) AS prompt_tokens\nFROM\n    ${database}.${table}\nWHERE\n    SpanKind = 'llm'\n    AND SpanAttributes['prompt_tokens'] != ''\n    AND StartTime BETWEEN $__fromTime AND $__toTime\nGROUP BY\n    user_id\nORDER BY\n    prompt_tokens DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Daily Prompt Token Usage by User",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n    toDate(StartTime) AS date,\n    ResourceAttributes['user_id'] AS user_id,\n    sum(toUInt32(SpanAttributes['prompt_tokens'])) AS prompt_tokens\nFROM\n    ${database}.${table}\nWHERE\n    SpanKind = 'llm'\n    AND SpanAttributes['prompt_tokens'] != ''\n    AND StartTime BETWEEN $__fromTime AND $__toTime\nGROUP BY\n    date,\n    user_id\nORDER BY\n    prompt_tokens DESC,\n    date ASC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Daily Token Usage for User ${user_id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n    toDate(StartTime) AS date,\n    sum(toUInt32(SpanAttributes['prompt_tokens'])) AS prompt_tokens,\n    sum(toUInt32(SpanAttributes['completion_tokens'])) AS completion_tokens,\n    sum(toUInt32(SpanAttributes['total_tokens'])) AS total_tokens\nFROM\n    ${database}.${table}\nWHERE\n    SpanKind = 'llm'\n    AND ResourceAttributes['user_id'] = '${user_id}'\n    AND SpanAttributes['prompt_tokens'] != ''\n    AND StartTime BETWEEN $__fromTime AND $__toTime\nGROUP BY\n    date\nORDER BY\n    date"
    }
   ]
  }
 ]
}